#!/usr/bin/env php
<?php

/*
 * Simple Spark Server for CVI Jatim
 * Just run: php spark serve
 */

// Check PHP version
if (version_compare(PHP_VERSION, '8.1', '<')) {
    echo "PHP 8.1 or higher is required. Current version: " . PHP_VERSION . "\n";
    exit(1);
}

// Get command line arguments
$command = $argv[1] ?? '';

if ($command === 'serve') {
    $host = 'localhost';
    $port = 8080;

    // Check if custom host/port provided
    for ($i = 2; $i < count($argv); $i++) {
        if (strpos($argv[$i], '--host=') === 0) {
            $host = substr($argv[$i], 7);
        } elseif (strpos($argv[$i], '--port=') === 0) {
            $port = (int)substr($argv[$i], 7);
        }
    }

    echo "Starting CVI Jatim server...\n";
    echo "Server will be available at: http://{$host}:{$port}\n";
    echo "Press Ctrl+C to stop the server\n\n";

    // Change to public directory and start server
    chdir(__DIR__ . '/public');
    $cmd = "php -S {$host}:{$port}";

    // Execute the command
    passthru($cmd);
} else {
    echo "CVI Jatim Spark Server\n";
    echo "Usage: php spark serve [--host=localhost] [--port=8080]\n";
    echo "Example: php spark serve\n";
    echo "Example: php spark serve --host=0.0.0.0 --port=3000\n";
}
?>